!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/bluegray/puml-theme-bluegray.puml

skinparam DefaultFontColor black
skinparam DefaultFontSize 18
skinparam DefaultFontName Roboto
skinparam DatabaseBorderColor #FFF
skinparam ComponentBorderColor #ADD8E6
skinparam QueueBorderColor #FFF
skinparam QueueFontColor #FFF
skinparam CloudBorderColor #ADD8E6

skinparam DatabaseBackgroundColor #FFD54F
skinparam QueueBackgroundColor #9c27b0
skinparam ArrowThickness 1

skinparam component {
    BackgroundColor<<external>> #607d8b
    FontColor<<external>> #fff
}
skinparam rectangle {
    BackgroundColor<<external>> #607d8b
    FontColor<<external>> #fff
}

!$output = "FF5722"
!$outputEvent = "FFC300"
!$input = "4CAF50"
!$processing = "03A9F4"
!$trigger = "6A1B9A"
!$manual = "D84315"

!$info = "BBDEFB"
!$warning = "FFE0B2"
!$error = "F8BBD0"

!$dev = "C8E6C9"
!$qa = "E1BEE7"
!$prod = "BBDEFB"

!$external = "607d8b"
!$playground = "FFD54F"
!$bronze = "D2B48C"
!$silver = "E0E0E0"
!$gold = "FFF176"
!$platinum = "B0BEC5"

skinparam backgroundColor #FFF
skinparam SequenceLifeLineBorderColor black

'--- config end ---
